### ISSUE TITLE
no output when using GZipEncoder

### ISSUE THREAD

**Issue by danieleades** [Nemo157/async-compression#109]
This is likely user error, but i'm hoping for some assistance here

the follow compresses a local directory and outputs to a `.tar` archive successfully

```rust
use async_std::{fs::File, path::Path};
use async_tar::Builder;
use futures::io::AsyncWrite;

async fn write_archive<W>(writer: W, src_directory: impl AsRef<Path>) -> std::io::Result<()>
where
    W: AsyncWrite + Unpin + Send + Sync,
{
    let mut archive_builder = Builder::new(writer);
    archive_builder.append_dir_all("", src_directory).await?;
    archive_builder.finish().await
}

#[async_std::main]
async fn main() {
    let file = File::create("foo.tar.gz").await.unwrap();
    write_archive(file, "sample-directory").await.unwrap();
}
```

i'm trying to add gzip compression and create a `.tar.gz` archive

this is what I have

```rust
use async_compression::futures::write::GzipEncoder;
use async_std::{fs::File, path::Path};
use async_tar::Builder;
use futures::io::AsyncWrite;

async fn write_archive<W>(writer: W, src_directory: impl AsRef<Path>) -> std::io::Result<()>
where
    W: AsyncWrite + Unpin + Send + Sync,
{
    let mut archive_builder = Builder::new(writer);
    archive_builder.append_dir_all("", src_directory).await?;
    archive_builder.finish().await
}

#[async_std::main]
async fn main() {
    let file = File::create("foo.tar.gz").await.unwrap();
    let encoder = GzipEncoder::new(file);
    write_archive(encoder, "sample-directory").await.unwrap();
}
```

this completes without error, but results in an empty archive.

what am I doing wrong?

(`async-compression = {version = "0.3.6", features = ["futures-io", "gzip"] }`)

**Comment by paolobarbolini** [comment]
I think you may have to shutdown `encoder` in order to be sure it writes it's internal buffer and closes the encode.

**Comment by danieleades** [comment]
> I think you may have to `close` `encoder` in order to be sure it writes it's internal buffer and closes the encode.

I doubt that's the case.

i sure hope not it's not the case anyway, since the writer is consumed and I have no way to call that method!

**Comment by paolobarbolini** [comment]
You should be able to get the writer back with [Builder::into_inner](https://docs.rs/async-tar/0.3.0/async_tar/struct.Builder.html#method.into_inner).

**Comment by Nemo157** [comment]
It feels like `async_tar::Builder::finish` should close the inner writer.

**Comment by danieleades** [comment]
> It feels like `async_tar::Builder::finish` should close the inner writer.

This was my instinct

**Comment by danieleades** [comment]
this works, though it looks a little clumsy

```rust
use async_compression::futures::write::GzipEncoder;
use async_std::{fs::File, path::Path};
use async_tar::Builder;
use futures::io::{AsyncWrite, AsyncWriteExt};

async fn write_archive<W>(writer: W, src_directory: impl AsRef<Path>) -> std::io::Result<()>
where
    W: AsyncWrite + Unpin + Send + Sync,
{
    let mut archive_builder = Builder::new(writer);
    archive_builder.append_dir_all("", src_directory).await?;
    archive_builder.finish().await?;

    archive_builder.into_inner().await?.close().await
}

#[async_std::main]
async fn main() {
    let file = File::create("foo.tar.gz").await.unwrap();
    let encoder = GzipEncoder::new(file);
    write_archive(encoder, "docker-context").await.unwrap();
}
```

I have to say I find that surprising behaviour

Thanks for the backup!

**Comment by Nemo157** [comment]
Maybe open an `async-tar` issue to discuss it there? At the very least if they don't want to change behaviour I think `finish` should document that it doesn't ensure the inner writer is closed and flushed.

**Comment by danieleades** [comment]
new issue in async-tar - https://github.com/dignifiedquire/async-tar/issues/9
