### ISSUE TITLE
Add tokio 1.0 support

### ISSUE THREAD

**Issue by messense** [Nemo157/async-compression#110]
https://tokio.rs/blog/2020-12-tokio-1-0

**Comment by loyd** [comment]
Is it planned to build `stream` feature based on `bytes` v1?

**Comment by Nemo157** [comment]
@loyd no, my current plan is to deprecate `stream`, probably later today. Take a look at the discussion from https://github.com/Nemo157/async-compression/pull/107#issuecomment-751285504 down for how to use `tokio-util` to map between streams-of-byte-vectors and io-streams.
