### ISSUE TITLE
bytes 1.0 support

### ISSUE THREAD

**Issue by jhpratt** [Nemo157/async-compression#116]
bytes 1.0 came out back in December. It would be great to have support for it, such that this crate can be used with the latest versions of a number of crates.

**Comment by Nemo157** [comment]
See discussion in #107 and #115, with 0.3.8 the `stream` feature is deprecated and migration options that support all versions of `bytes` are documented on https://docs.rs/async-compression/0.3.8/async_compression/stream/index.html
