### ISSUE TITLE
async_compression::tokio::bufread::ZstdDecode: read_buf return 0 after first read

### ISSUE THREAD

**Issue by rohitjoshi** [Nemo157/async-compression#121]
I am trying to use streaming compression and decompression using tokio. Compression works fine but while streaming decompression, it only reads size of buffer one time and returns 0 for subsequent read.
1. How do I enable streaming read where it reads file content, decompress and allow to process uncompressed data? 
2. tokio::io:BufReader supports `read_line()` method but not able to use with `async_compression::tokio::bufread::ZstdDecoder`

```
#[tokio::test]
async fn streaming_zstd_test() {

    let lru_content = include_bytes!("lru.txt");
    println!("Content size of LRU file:{}", lru_content.len());

    let file_path = "/tmp/compression_lru";
    if let Ok(file) = File::create(file_path).await {
        let data = BufWriter::with_capacity(1024, file);
        let mut enc = async_compression::tokio::write::ZstdEncoder::new(data);
        tokio::io::AsyncWriteExt::write_all(&mut enc, lru_content).await.unwrap();
        enc.flush().await.unwrap();
    }
    if let Ok(file) = File::open(file_path).await {
        if let Ok(meta) = file.metadata().await {
            println!("Size of compressed file:{} : {}", file_path, meta.len());
        }
        let  data = BufReader::with_capacity(4096, file);
        let mut dec = async_compression::tokio::bufread::ZstdDecoder::new(data);
        let mut buffer = bytes::BytesMut::with_capacity(4096);
        let mut expcted_bytes = 0;
        while let Ok(num_bytes) = dec.read_buf(&mut buffer).await {
            println!("num_bytes:{} read", num_bytes);
            expcted_bytes += num_bytes;
             buffer.clear();
            if num_bytes == 0 {
                println!("num_bytes read zero. exiting");
                println!("num_bytes:{} read, total expcted_bytes:{}", num_bytes, expcted_bytes);

                break;
            }
        }
        assert_eq!(lru_content.len(), expcted_bytes);
    }
    tokio::fs::remove_file(file_path).await.unwrap();
}
```

Here is the output:
```
Content size of LRU file:11356
Size of compressed file:/tmp/compression_lru : 4076
num_bytes:4096 read
num_bytes:0 read
num_bytes read zero. exiting
num_bytes:0 read, total expcted_bytes:4096
thread 'cache_updater::streaming_zstd_test' panicked at 'assertion failed: `(left == right)`
  left: `11356`,
 right: `4096`', kanudo/src/cache_updater.rs:352:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test cache_updater::streaming_zstd_test ... FAILED
```

**Comment by Nemo157** [comment]
> 2\. tokio::io:BufReader supports `read_line()` method but not able to use with `async_compression::tokio::bufread::ZstdDecoder`

You can wrap `ZstdDecoder` in a `BufReader` to get the methods like `read_line()` that rely on buffering for performance.

```rust
enc.flush().await.unwrap();
```

This should be

```rust
enc.shutdown().await.unwrap();
```

You must always close an encoder to ensure it finishes writing out the final block correctly (and that implicitly flushes).

Technically I think there is a bug here, that `flush` _should_ force completing the current block, so that you do receive all data back when reading from it, but then because of not closing the encoder you would probably receive an error after the data.

**Comment by rohitjoshi** [comment]
Thank you. `enc.shutdown().await.unwrap();` did work.

**Comment by rohitjoshi** [comment]
In my use-case, I have number file LRU cache backup files which needs to be loaded into in-memory LRU cache as soon as possible. The approach I have taken is reading these files asynchronously (in parallel using tokio::task::spawn), parse them and add key-val in-memory cache. 
Function to set key-val in cache already uses async function so with spawn_blocking, it would not allow me to call these methods.
