### ISSUE TITLE
`write::XzDecoder` fails when passed data piecewise

### ISSUE THREAD

**Issue by l0calh05t** [Nemo157/async-compression#126]
```rust
use tokio::io::{AsyncReadExt, AsyncWriteExt};

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), tokio::io::Error> {
	let mut result = Vec::new();
	tokio::fs::File::open(r"bela_image_v0.3.8b.img.xz")
		.await?
		.read_to_end(&mut result)
		.await?;
	println!("{}", result.len());
	let file = tokio::fs::File::create("bela_image_v0.3.8b.img").await?;
	let mut decoder = async_compression::tokio::write::XzDecoder::new(file);
	//for chunk in (&result).chunks(123478) {
	//	decoder.write(chunk).await?;
	//}
	decoder.write_all(&result).await?;
	decoder.shutdown().await?;
	Ok(())
}
```

While the above `write_all` succeeds, the commented-out "chunked" version fails with `Error: Custom { kind: Other, error: Data }`. I believe it should work

**Comment by Nemo157** [comment]
The issue is probably that `decoder.write(chunk).await?` is only writing a portion of the chunk, you need to either be checking the return value to see how much it wrote, or use `decoder.write_all(chunk).await?` in the loop to write the entirety of each chunk out.

**Comment by l0calh05t** [comment]
Thanks! That seems to solve the issue. I guess I didn't read the docs properly. Assuming `write` is designed for doing your own buffering, I also tried

```rust
	let mut buf = Vec::new();
	for chunk in (&result).chunks(123478) {
		buf.extend_from_slice(chunk);
		let n = decoder.write(&buf).await?;
		buf = buf.split_off(n);
	}
	println!("remainder {}", buf.len());
	decoder.write_all(&buf).await?;
```

but the `write`-loop only ever writes a tiny fraction of the content, leaving almost the entirety of the work to the final `write_all`:

```
469734440
remainder 467652205
```

So the issue is solved for me, but the `write`-behavior should probably be examined further.

**Comment by Nemo157** [comment]
There is an 8KiB buffer in the write path, so at most only 8KiB of decompressed data will be written per-call, and a corresponding smaller amount of input data will be consumed.

https://github.com/Nemo157/async-compression/blob/f82571abcf3c9ce8c7e191c63af8242530329c12/src/tokio/write/buf_writer.rs#L16

It would be nice to allow configuring this, but my preferred approach for that would be having an external `AsyncBufWrite` trait to use to allow passing in anything that has a buffered writer, and I haven't really seen any interest elsewhere in having such a trait.

For your usecase, it might make more sense to wrap the input file in a `bufread::XzDecoder`, that way you could use `tokio::io::BufReader::with_capacity` to configure a larger buffer size.
