### ISSUE TITLE
Linking error due to multiple definition of zstd symbols in release mode

### ISSUE THREAD

**Issue by rohitjoshi** [Nemo157/async-compression#127]
Adding a cross reference for linking error due to multiple definition of zstd issue: https://github.com/rust-rocksdb/rust-rocksdb/issues/535

**Comment by Nemo157** [comment]
Seems like a `librocksdb-sys` bug, and more related to its interaction with `zstd-sys` than anything to do with `async-compression`.

**Comment by Nemo157** [comment]
It sounds like this is fixed on the rust-rocksdb side.
