### ISSUE TITLE
Multiple zstd frames within a single input stream not supported

### ISSUE THREAD

**Issue by mlartz** [Nemo157/async-compression#130]
The zstd spec allows for multiple frames within a single file: https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html#comp_frames .  This means that it is perfectly allowable to concatenate zstd files together e.g.:

```
echo "Hello World 1" >> file1
echo "Hello World 2" >> file2
zstd file1
zstd file2
cat file1.zst file2.zst > file3.zst
```

Based on my reading of the code, `async-compression`'s zstd decoder uses the results of the underlying `zstd::stream::raw::Operation::run_on_buffers` (which just proxies to `zstd::stream::raw::Operation::run`). The return value of `0` from `run` is a "hint" that could indicate the end of a frame, but not necessarily the end of the input (i.e. EOF).  In reading zstd files with mutliple frames, `async-compression` (using `async_compression::tokio::bufread::ZstdDecoder`) only reads the first zstd frame and closes the output stream, as it seems to use this `0` return value from `run` as indicating the end of the input.

I'm new to Rust, but if there is a workaround, I'd love to hear it!

References:
- `async-compression` zstd decoder: https://github.com/Nemo157/async-compression/blob/0.3.8/src/codec/zstd/decoder.rs#L25-L37
- `zstd` `run`/`run_on_buffers` with comments about the return values: https://github.com/gyscos/zstd-rs/blob/0.8.0/src/stream/raw.rs#L18-L49
- Example of `zio` reader in `zstd` to handle the difference between end of frame and end of file: https://github.com/gyscos/zstd-rs/blob/0.8.0/src/stream/zio/reader.rs#L101-L150

**Comment by mlartz** [comment]
I *think* that a single line change to https://github.com/Nemo157/async-compression/blob/0.3.8/src/codec/zstd/decoder.rs#L36 to always return `Ok(true)` will solve the issue, as the generic decoder already has logic to switch the state to `Flushing` at the end of a stream.  That said, I don't fully understand the codebase (nor zstd) to comment on whether this is "correct" for all cases.

**Comment by Nemo157** [comment]
There is the [`multiple_members`](https://docs.rs/async-compression/0.3.8/async_compression/tokio/bufread/struct.ZstdDecoder.html#method.multiple_members) toggle to enable automatically resuming decoding of following frames until EOF is reached. The reason this is toggleable is to support cases where there is a compressed frame of data followed by other non-`zstd` data without something like a length-prefix to constrain the decoder.

**Comment by mlartz** [comment]
I had hoped that it would be that simple ... and it is!  Thanks!

And thanks for the crate.  I've both learned a lot from the code, and am using it heavily in my new project.
