### ISSUE TITLE
zstd encoder default level says 0, while it's usually 3

### ISSUE THREAD

**Issue by hdhoang** [Nemo157/async-compression#156]
hello, [Level::Default enum for zstd returns 0i32](https://github.com/Nemo157/async-compression/blob/a23d7a6076b45d3c409ec696e25faeaabdc685c0/src/lib.rs#L247), however zstd commandline default as well as [zstd crate default constant](https://docs.rs/zstd/latest/zstd/constant.DEFAULT_COMPRESSION_LEVEL.html) is `3i32`.

in commit 62557bf we lost a comment explaining that

>          algos!(@algo zstd ["zstd"] ZstdDecoder ZstdEncoder<$inner> {
>           /// The `level` argument here can range from 1-21. A level of `0` will use zstd's default, which is `3`

With `0` being outside the range 1-21, can we change it to the libzstd constant instead?

Thanks for your time!

**Comment by Nemo157** [comment]
By passing `0` we are telling the `zstd` crate to use its default (<https://docs.rs/zstd/latest/zstd/stream/write/struct.Encoder.html#method.new>)). This could be changed to use the const instead though to be a little more explicit, happy to take a PR.
