### ISSUE TITLE
Brotli compression performace

### ISSUE THREAD

**Issue by barvirm** [Nemo157/async-compression#174]
Hello, I started to use `tower-http` compression layer, and I notice a significant slowdown in my server.
After some measurements, I found out that, the Brotli encoder is able to compress my file (300Kb) in 10ms, but after compression, the encoder state is changed to `BROTLI_OPERATION_FLUSH ` which takes 3.5s.

**Comment by barvirm** [comment]
Minimal example: 
```rust
use async_compression::tokio::bufread::BrotliEncoder;
use tokio::{fs::File, io::AsyncReadExt};
use tokio_util::io::ReaderStream;

use std::time::Instant;

#[tokio::main]
async fn main() {
    // File with size: 1,7 MB
    let file = File::open("test.bin").await.unwrap(); 
    let reader = tokio::io::BufReader::new(file);
    let mut buffer = Vec::with_capacity(2*1000*1000);

    let start = Instant::now();

    let mut encoder = BrotliEncoder::new(reader);
    encoder.read_to_end(& mut buffer).await.unwrap();

    let elapsed = start.elapsed();

    // +/- 20s
    println!("elapsed: {:#?}", elapsed);
}
```

**Comment by Nemo157** [comment]
I did a slight modification to test with random data (and try eliminate any IO times by reading everything at once):

```rust
    let file = File::open("/dev/urandom").await.unwrap();
    let reader = BufReader::with_capacity(2_000_000, file.take(1_700_000));
```

I don't get 20s, but I do see 2.5s in debug mode and 500ms in release which still seems way too long.

**Comment by Nemo157** [comment]
Actually, that still doesn't read everything at once, this does:

```rust
    let file = File::open("/dev/urandom").await.unwrap();
    let mut bytes = Vec::with_capacity(2_000_000);
    file.take(1_700_000).read_to_end(&mut bytes).await.unwrap();

    let reader = std::io::Cursor::new(bytes);
```

I added some extra debugging after https://github.com/Nemo157/async-compression/blob/79326077ae6ed4f8499e31e83ab02f7a9c826ac9/src/codec/brotli/encoder.rs#L39

```rust
eprintln!("BrotliEncoderCompressStream input {}/{} output {}/{} in {:?}", input_len, in_buf.len(), output_len, out_buf.len(), start.elapsed());
```

which gave in `--release`:

```
BrotliEncoderCompressStream input 1700000/1700000 output 1310724/2000000 in 492.528302ms
BrotliEncoderCompressStream input 0/0 output 389284/689276 in 57.598134ms
elapsed: 550.742049ms
```

So there's no real overhead from `async-compression`, it's just `brotli` itself being this slow at the default level. Switching to `Level::Fastest` I get 1.5ms in release (which is probably the level that should be used for streaming compression).

**Comment by barvirm** [comment]
> ```rust
>     let file = File::open("test.bin").await.unwrap(); 
>     let reader = BufReader::new(file);
> ```

With this modification, I have the same results.

**Comment by barvirm** [comment]
> I did a slight modification to test with random data (and try eliminate any IO times by reading everything at once):
> 
> ```rust
>     let file = File::open("/dev/urandom").await.unwrap();
>     let reader = BufReader::with_capacity(2_000_000, file.take(1_700_000));
> ```
> 
> I don't get 20s, but I do see 2.5s in debug mode and 500ms in release which still seems way too long.

With this modification, I have the same results.

**Comment by barvirm** [comment]
Intrestingly on Windows 10 x64, with modification like this:
```rust
    let file = File::open("test.bin").await.unwrap(); 
    let reader = BufReader::with_capacity(2_000_000, file.take(1_700_000));
```

It still takes 23s.

**Comment by barvirm** [comment]
Ou so only this line changes the time from 3 to 23s.
```rust
// 23
let file = File::open("test.bin").await.unwrap(); 
// 3
let file = File::open("/dev/urandom").await.unwrap();
```

**Comment by barvirm** [comment]
In the end, there is no problem with compression speed. The problem was the underlying data in `test.bin` file. If I created a file of the same size and fill it with random data, the compression speed is fine. When is the compression level set to `Fastest` timing results are almost identical.
