### ISSUE TITLE
Brotli implementation choice

### ISSUE THREAD

**Issue by jebrosen** [Nemo157/async-compression#39]
Currently the [`brotli2`](https://crates.io/crates/brotli2) crate is used for brotli compression, which has a `-sys` dependency. These crates can be inconvenient to deal with because of `links=`, and `brotli-sys` also bundles a relatively outdated version of [google/brotli](https://github.com/google/brotli). Would it be reasonable to support the [`brotli`](https://crates.io/crates/brotli) crate instead of or in addition to `brotli2`?

**Comment by Nemo157** [comment]
Certainly, if it is capable of being integrated, seeing undocumented functions like [this](https://docs.rs/brotli/3.3.0/brotli/struct.DecompressorCustomIo.html) which I _think_ might be the integration point we need to use gives my pause though.

**Comment by jebrosen** [comment]
...wow, that type signature is annoying. That's unfortunate.

I'm willing to do the legwork myself when I get time, and if I like how it turns out I can propose it again then.

**Comment by Nemo157** [comment]
Great! Feel free to ping me with any questions if you get round to it (here, or I’m active on either of the discords)

**Comment by dekellum** [comment]
I would agree that the _brotli_ rustdoc isn't great but I managed to integrate it in _barc_ and _body-image-futio_ crates, though perhaps async-compression has more needs?  I'm considering using this crate for streaming (de-)compression but I have a brotli dependency already, would rather not have brotli2 as well.   So I would just like to note my interest here.

**Comment by Nemo157** [comment]
The integration to a codec is relatively small, it just needs an implementation of [these two traits](https://github.com/Nemo157/async-compression/blob/c879f434481be47e1da648d217f8842069730943/src/codec/mod.rs#L34). I would happily accept a PR switching the [brotli implementations](https://github.com/Nemo157/async-compression/tree/master/src/codec/brotli) to using the `brotli` crate if that is the better option (I haven’t really looked into how it compares).

**Comment by dekellum** [comment]
I'd suggest keeping brotli2 as a valid alternative, by feature gate.  I might be faster if not all rust.

**Comment by jebrosen** [comment]
> I'm willing to do the legwork myself when I get time

Sorry to say this issue has since fallen quite low on my priority list.

---

As far as I can tell most of the `brotli` crate's "high-level" interfaces assume a synchronous `Read` API, even the ones named e.g. `CompressorWriterCustomIo`. [`BrotliEncoderCompressStream`](https://docs.rs/brotli/3.3.0/brotli/enc/encode/fn.BrotliEncoderCompressStream.html) looks the most promising to me in terms of providing an API that accepts partial input and output, but I find those APIs *very* difficult to follow overall and I would hesitate to implement anything on top of them without at a minimum knowing details of the brotli algorithm.
