### ISSUE TITLE
Moving the repository to a new home

### ISSUE THREAD

**Issue by yoshuawuyts** [Nemo157/async-compression#52]
The rustasync org has officially been sunset, and all projects are moving to a new home. As the maintainers of the project you have a choice where to move it to.

I'd like to offer the option to join the [http-rs](https://github.com/http-rs) org, joining many of the other network-related projects that used to be part of the `rustasync` org. Let me know, and I'll send you both an invite. But in the end, the choice is up to you.

Thanks for having been part of the Rust Async Ecosystem WG; it's been a pleasure!

cc/ @Nemo157 @fairingrey

**Comment by Nemo157** [comment]
We discussed this a while back and for now I'd prefer to move the repo under my account (but will definitely add you as a co-maintainer for bus factor).

To do so I think either I need to be granted admin access, or you'll have to move the repo to your account then transfer it to me.

Thanks a lot for all your work with the WG :heart:, I'm very excited to see where Tide goes.

**Comment by yoshuawuyts** [comment]
On it!

**Comment by yoshuawuyts** [comment]
> Nemo157 already has a repository in the rustasync/async-compression network and You can only transfer a repository from an organization to yourself at this time.

@Nemo157 I think you may need to delete a similarly-named fork first.

**Comment by Nemo157** [comment]
@yoshuawuyts deleted my fork

**Comment by yoshuawuyts** [comment]
@nemo157 transfer request initiated!

**Comment by Nemo157** [comment]
Thanks, I've added you as an owner on crates.io just in case.
