### ISSUE TITLE
Add tokio-io trait support

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/async-compression#57]
Add `tokio::{bufread, write}` modules based on traits from `tokio-io 0.2`. Until that has a non-alpha release the modules should be extra gated behind some unstable flag.

**Comment by Nemo157** [comment]
Probably worth waiting at least until https://github.com/tokio-rs/tokio/pull/1744 is sorted out for preview support.

**Comment by Nemo157** [comment]
Given Tokio's planned breaking change rate and that #1744 will almost certainly result in at least one of those breaking changes hitting `tokio-io` I think the best approach would be to start with adding a `tokio-02` module and feature (if `tokio` and `tokio-io` versioning diverges this may become a bit weird, but we can deal with it then). Once Tokio 1.0 releases that can be given the primary `tokio` module/feature name.

**Comment by dnaka91** [comment]
First of all thank you @Nemo157 for the big effort of building this crate.

Is there any recent progress on this matter?

I'm currently trying to use this crate but my input is a `Pin<Box<dyn AsyncRead + Send>>` with `tokio`'s `AsyncRead` and I couldn't find any way of converting it into `futures`'s `AsyncRead` to give it as an input to `async_compression::futures::bufread::GzipEncoder`.

As far as I understand the `tokio-io` crate is now part of the main `tokio` crate with the IO traits behind a feature flag.

Or is there already some easy way of converting between `tokio`'s and `futures`'s traits maybe?

**Comment by Nemo157** [comment]
There is the [`tokio-util::compat`](https://docs.rs/tokio-util/0.3.1/tokio_util/compat/index.html) module that gives bidirectional compatibility (though not for `AsyncBufRead` so you might end up with double-buffering). I do think it's about time this happened though, I don't think it'll be very difficult to throw together.

**Comment by dnaka91** [comment]
Thanks for the tip 👍 

The `tokio-util` crate was exactly what I needed and I didn't end up with any double-buffering.

Would be great to have the `tokio` traits directly supported by this crate in the future. Maybe I can give it a try to implement this in the next few days. I haven't worked on the low level parts of async/await yet though, so we'll see how far I get 😅

**Comment by dnaka91** [comment]
So I tried adding `tokio` support on Sunday evening, but I had little luck.
I don't understand all the code of this repo and am fairly a beginner at the more lower level of Rust's async/await. In the end I had something working, but it was all just copy & paste from the `futures` module and there was ton's of duplicate code.

I better leave this integration to you 🙇 😅
