### ISSUE TITLE
Hide implementation details

### ISSUE THREAD

**Issue by Nemo157** [Nemo157/async-compression#71]
Currently the `flate2` and `brotli2` (soon to be `brotli`, see #70) libraries are exposed publicly through configuring the constructors of the `Encoder`s using them. This should be hidden so that changing which library is used is not a breaking change.

Main idea would be to replace the re-exports with locally defined configuration parameters, then map those to the underlying implementation internally.

**Comment by daxpedda** [comment]
I can start write a PR for this.
Is basically copying [`CompressParams`](https://docs.rs/brotli2/0.3.2/brotli2/struct.CompressParams.html) alright?

**Comment by Nemo157** [comment]
TBH, skimming that API I don’t really like it. I would use `fn(self, ...) -> Self` methods since it should be trivially copyable, and probably start with only supporting `quality` until other parameters are requested.

**Comment by daxpedda** [comment]
Sure, will start on it when #70 is merged.
