### ISSUE TITLE
Handle concatenated `.gz` files

### ISSUE THREAD

**Issue by bekh6ex** [Nemo157/async-compression#75]
I wanted to process a huge `.gz` file without downloading it which actually was concatenation of multiple `.gz` files. This is rather common practice to be able to utilzie multiple cores while compressing big amount of data.

`GzipDecoder` failed to handle it properly - it stopped after the first "chunk" and didn't even output an error.

`gzip` utility decompresses the file without any problems. I guess, so should do `GzipDecoder`.

**Comment by Nemo157** [comment]
Thanks for raising this, this is something I've been meaning to look into since seeing `flate2`'s `MultiGzDecoder`.

It appears that the `.gz` file format does specify that concatenated members should be treated as a single data stream, but there are usecases where you wouldn't want this, e.g. if you were to send a stream of messages with headers + gzipped data, you can currently rely on the decoder detecting the end of the gzipped data and then reuse the underlying reader

```rust
async fn read_msgs(reader: impl AsyncBufRead) -> io::Result<Vec<Msg>> {
  pin_mut!(reader);
  let mut msgs = Vec::new();
  while poll_fn(|| reader.as_mut().poll_fill_buf().map(|b| !b.is_empty())).await? {
    let header = read_header(reader.as_mut())?;
    let mut data = Vec::new();
    GzipDecoder::new(reader.as_mut()).read_to_end(&mut data).await?;
    msgs.push(Msg::new(header, data));
  }
}
```

I think I would prefer to keep the current behaviour for usecases like this and consistency with all the other decoders, but add some way to support concatenated members. Either a separate type like `MultiGzipDecoder`, or a function on `GzipDecoder` like `fn decode_multiple_members(&mut self, bool)`.

**Comment by bekh6ex** [comment]
I'm not sure that I got your point. Do you have in mind some real life examples of such usecase?

And also, can you add a test for this behaviour? I can then try to make it work.

PS: I really need this feature for my project. :)

**Comment by bekh6ex** [comment]
BTW, Lzip archives have the same property:

> Lzip will correctly decompress a file which is the concatenation of two or more compressed files. The result is the concatenation of the corresponding decompressed files.

From https://www.nongnu.org/lzip/lzip.html

**Comment by jpiepkow** [comment]
I second this issue. This crate is used downstream in reqwest and fails on any concatenated gzip return(in my case common crawl).

**Comment by Nemo157** [comment]
I've [pushed a branch including a test for the behaviour I would expect](https://github.com/Nemo157/async-compression/commit/83e691ec18ccf049a8564f4ff26eef269e65419e) (the decoder reads until the end of compressed data and stops). That works with all implementations except `zstd` (which just appears to consume the bytes and ignore them, not even producing an error...), I still need to look into whether this is a limitation of the encoding format, or the implementation.

Thinking about it what I think could make sense is to expose an API on the `bufread::*Decoder` like 

```rust
        impl<R: futures_io::AsyncBufRead> $name<R> {
            /// Configure multi-member decoding, if enabled this will reset the decoder state
            /// when reaching the end of a compressed member and expect either EOF or
            /// another compressed member to follow it in the stream.
            pub fn multiple_members(&mut self, enabled: bool) -> &mut R {
                ...
            }
        }
```

---

@jpiepkow `reqwest` 0.9 didn't appear to use the `flate2::read::MultiGzDecoder`, so it would have only handled a single member. Testing locally `curl` also doesn't appear to handle concatenated gzip for either content-encoding or transfer-encoding. Do you have any public example hosts returning this?

```console
> { echo -ne "HTTP/1.1 200 OK\r\nContent-Encoding: gzip\r\nConnection: close\r\n\r\n"; echo -n "Hello\r\n" | gzip; echo -n "World\r\n" | gzip } | nc -l 6894
GET / HTTP/1.1
Host: localhost:6894
User-Agent: curl/7.68.0
Accept: */*
Accept-Encoding: deflate, gzip
```

```console
> curl -i --compressed http://localhost:6894
HTTP/1.1 200 OK
Content-Encoding: gzip
Connection: close

Hello
curl: (23) Failed writing received data to disk/application
```

**Comment by jpiepkow** [comment]
I am currently using a forked version of reqwest pointing to the following PR:
https://github.com/Nemo157/async-compression/pull/74

It works for my usecase but I wouldn't mind upstream support(so I don't have to fork) at some point.

**Comment by Nemo157** [comment]
As another reference, while looking at #81 I found this in the [XZ file format description](https://tukaani.org/xz/xz-file-format.txt):

>         While a typical file contains only one Stream and no Stream
>        Padding, a decoder handling standalone .xz files SHOULD support
>        files that have more than one Stream or Stream Padding.
>
>        In contrast to standalone .xz files, when the .xz file format
>        is used as an internal part of some other file format or
>        communication protocol, it usually is expected that the decoder
>        stops after the first Stream, and doesn't look for Stream
>        Padding or possibly other Streams.

Which supports my plan of defaulting to decoding till the end of a single stream/member and having an option to enable multiple members.

**Comment by firasuke** [comment]
> BTW, Lzip archives have the same property:
> 
> > Lzip will correctly decompress a file which is the concatenation of two or more compressed files. The result is the concatenation of the corresponding decompressed files.
> 
> From https://www.nongnu.org/lzip/lzip.html

Is `lzip` supported by `async-compression` though?
